name: Setup
description: 'Setup stuff'
runs:
  using: "composite"
  steps:
    - name: set up JDK 20
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
      with:
        distribution: 'zulu'
        java-version: '20'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@8cbcb9948b5892387aed077daf6f90e1f0ba5b27 # v2.11.0
