name: Setup
description: 'Setup stuff'
inputs:
  encryption_key:
    default: ""
    description: "Encryption key for Gradle Configuration Cache"
runs:
  using: "composite"
  steps:
    - name: set up JDK 23
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        distribution: 'zulu'
        java-version: '23'
    - name: Set up jemalloc
      uses: kaeawc/setup-jemalloc@fecdd1e4fa3bd5592b055c8e0a1b609e21f46837 # v0.0.1
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
      with:
        cache-encryption-key: ${{ inputs.encryption_key }}

# Stolen from here https://github.com/kaeawc/android-build/blob/a86b15e3cbc5d36339a97d09f46c7a22e276ff7f/.github/actions/gradle-task-run/action.yml#L140
    - name: "Restore Android SDK Platform Tools"
      id: cache-android-platform-tools
      uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      with:
        path: |
          /usr/local/lib/android/sdk/platform-tools
          /home/runner/.config/.android/cache
        key: v2-${{ runner.os }}-android-platform-tools
    - name: Setup Android SDK
      if: steps.cache-android-platform-tools.outputs.cache-hit != 'true'
      uses: android-actions/setup-android@00854ea68c109d98c75d956347303bf7c45b0277 # v3.2.1
    - name: "Save Android SDK Platform Tools"
      uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      if: steps.cache-android-platform-tools.outputs.cache-hit != 'true'
      with:
        path: |
          /usr/local/lib/android/sdk/platform-tools
          /home/runner/.config/.android/cache
        key: v2-${{ runner.os }}-android-platform-tools
