name: Setup
description: 'Setup stuff'
inputs:
  encryption_key:
    default: ""
    description: "Encryption key for Gradle Configuration Cache"
runs:
  using: "composite"
  steps:
    - name: set up JDK 21
      uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4
      with:
        cache-encryption-key: ${{ inputs.encryption_key }}
