name: Setup
description: 'Setup stuff'
runs:
  using: "composite"
  steps:
    - name: set up JDK 19
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: 'zulu'
        java-version: '19'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
