name: Setup
description: 'Setup stuff'
inputs:
  encryption_key:
    default: ""
    description: "Encryption key for Gradle Configuration Cache"
runs:
  using: "composite"
  steps:
    - name: set up JDK 23
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        distribution: 'zulu'
        java-version: '23'
    - name: Set up jemalloc
      uses: kaeawc/setup-jemalloc@97ffdab77f76db0584b4d9cfb036fab6457d5526 # v0.0.3
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@473878a77f1b98e2b5ac4af93489d1656a80a5ed # v4
      with:
        cache-encryption-key: ${{ inputs.encryption_key }}

# Stolen from here https://github.com/kaeawc/android-build/blob/a86b15e3cbc5d36339a97d09f46c7a22e276ff7f/.github/actions/gradle-task-run/action.yml#L140
    - name: "Restore Android SDK Platform Tools"
      id: cache-android-platform-tools
      uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      with:
        path: |
          /usr/local/lib/android/sdk/platform-tools
          /home/runner/.config/.android/cache
        key: v2-${{ runner.os }}-android-platform-tools
    - name: Setup Android SDK
      if: steps.cache-android-platform-tools.outputs.cache-hit != 'true'
      uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
    - name: "Save Android SDK Platform Tools"
      uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      if: steps.cache-android-platform-tools.outputs.cache-hit != 'true'
      with:
        path: |
          /usr/local/lib/android/sdk/platform-tools
          /home/runner/.config/.android/cache
        key: v2-${{ runner.os }}-android-platform-tools
