name: Setup
description: 'Setup stuff'
inputs:
  encryption_key:
    default: ""
    description: "Encryption key for Gradle Configuration Cache"
runs:
  using: "composite"
  steps:
    - name: set up JDK 23
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        distribution: 'zulu'
        java-version: '23'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
      with:
        cache-encryption-key: ${{ inputs.encryption_key }}
