# Copyright (C) 2026 Nicholas Doglio
# SPDX-License-Identifier: MIT
toolchainUrl.FREE_BSD.AARCH64=https\://api.foojay.io/disco/v3.0/ids/40e63d8ffab23bbce9fcbdbad921677b/redirect
toolchainUrl.FREE_BSD.X86_64=https\://api.foojay.io/disco/v3.0/ids/508a52e159add130a40c351c6547d91d/redirect
toolchainUrl.LINUX.AARCH64=https\://api.foojay.io/disco/v3.0/ids/40e63d8ffab23bbce9fcbdbad921677b/redirect
toolchainUrl.LINUX.X86_64=https\://api.foojay.io/disco/v3.0/ids/508a52e159add130a40c351c6547d91d/redirect
toolchainUrl.MAC_OS.AARCH64=https\://api.foojay.io/disco/v3.0/ids/6e757c4898a77cb48eb4a880322304a4/redirect
toolchainUrl.MAC_OS.X86_64=https\://api.foojay.io/disco/v3.0/ids/84b4d326fcca79a9a05e06a715b43564/redirect
toolchainUrl.UNIX.AARCH64=https\://api.foojay.io/disco/v3.0/ids/40e63d8ffab23bbce9fcbdbad921677b/redirect
toolchainUrl.UNIX.X86_64=https\://api.foojay.io/disco/v3.0/ids/508a52e159add130a40c351c6547d91d/redirect
toolchainUrl.WINDOWS.X86_64=https\://api.foojay.io/disco/v3.0/ids/36c926b5f1c630e9e2b0599c22747151/redirect
toolchainVendor=AZUL
toolchainVersion=26
