[versions]
agp = "8.0.0"
kotlin = "1.8.20"
ktfmt = "0.43"
lint = "31.0.0"
detekt = "1.22.0"
dagger = "2.45"
ktlint = "0.49.0"
kover = "0.7.0-Beta"
spotless = "6.18.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
lint = { id = "com.android.lint", version.ref = "agp" }
doctor = { id = "com.osacky.doctor", version = "0.8.1" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version = "1.20.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradleVersions = { id = "com.github.ben-manes.versions", version = "0.46.0" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

[libraries]
spotless-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kover-gradle = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
anvil = { module = "com.squareup.anvil:annotations", version = "2.4.5" }

lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
lint = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
lint-testUtils = { module = "com.android.tools:testutils", version.ref = "lint" }

detekt-ruleauthors = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ruleauthors", version.ref = "detekt" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }

ktlint-core = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "ktlint" }
ktlint-test = { module = "com.pinterest.ktlint:ktlint-test", version.ref = "ktlint" }

junit = { module = "junit:junit", version = "4.13.2" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.11" }

[bundles]
lintApi = ["lint-api", "lint-checks"]
lintTest = ["lint", "lint-tests", "lint-testUtils"]
test = ["junit", "truth", "testParameterInjector"]
