[versions]
agp = "8.4.0"
desugar = "2.0.4"
kotlin = "1.9.24"
ktlint = "1.2.1"
lint = "31.4.0"
detekt = "1.23.6"
kover = "0.8.0"
spotless = "6.25.0"
jdk = "21"
sort = "0.6"
dagger = "2.51.1"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
lint = { id = "com.android.lint", version.ref = "agp" }
android-app = { id = "com.android.application", version.ref = "agp" }
doctor = { id = "com.osacky.doctor", version = "0.10.0" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version = "1.31.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.24-1.0.20" }
sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "sort" }
anvil = { id = "com.squareup.anvil", version = "2.4.9" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }

[libraries]
spotless-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kover-gradle = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
sortDependencies-gradle = { module = "com.squareup.sort-dependencies:com.squareup.sort-dependencies.gradle.plugin", version.ref = "sort" }

autoService-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.1.1" }
autoService-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version = "1.1.0" }

lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }

desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

ktlint = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

detekt-ruleauthors = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ruleauthors", version.ref = "detekt" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }

androidx-gradle-lints = { module = "androidx.lint:lint-gradle", version = "1.0.0-alpha01" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-activity = { module = "androidx.activity:activity", version = "1.9.0" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }

junit = { module = "junit:junit", version = "4.13.2" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.16" }

[bundles]
lintTest = ["lint-api", "lint-tests"]
test = ["junit", "testParameterInjector"]
