[versions]
agp = "8.12.1"
desugar = "2.1.5"
dependencyAnalysis = "3.0.1"
kotlin = "2.2.10"
ktfmt = "0.58"
lint = "31.12.1"
detekt = "1.23.8"
kover = "0.9.1"
spotless = "7.2.1"
jdk = "24"
jdkTarget = "17"
sort = "0.14"
dagger = "2.57.1"

[plugins]
convention-kotlin = { id = "dev.whosnickdoglio.convention.kotlin", version = "0.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
lint = { id = "com.android.lint", version.ref = "agp" }
android-app = { id = "com.android.application", version.ref = "agp" }
doctor = { id = "com.osacky.doctor", version = "0.12.1" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version = "2.2.10-2.0.2" }
sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "sort" }
anvil = { id = "dev.zacsweers.anvil", version = "0.4.1" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }

[libraries]
autoService-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.1.1" }
autoService-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version = "1.2.0" }

lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }

desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

# Only present to trigger automatic renovate updates
ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }

detekt-ruleauthors = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ruleauthors", version.ref = "detekt" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }

androidx-core = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-activity = { module = "androidx.activity:activity", version = "1.10.1" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }

junit = { module = "junit:junit", version = "4.13.2" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.18" }

[bundles]
lintTest = ["lint-api", "lint-tests"]
test = ["junit", "testParameterInjector"]
